BOARD_SIZE = 8

ROLE_IMAGES_PATH = "./images"

WHITE = 255, 255, 255
BLACK = 0, 0, 0
GREY = 178, 178, 178

BACKGROUND_COLOR = WHITE
TILE_COLOR = BLACK
MOVE_COLOR = GREY

WINDOW_SIZE = 640
TILE_SIZE = WINDOW_SIZE // BOARD_SIZE

ROLE_IMAGE_SIZE = TILE_SIZE * 0.7
ROLE_IMAGE_OFFSET = TILE_SIZE * .3 / 2

MOVE_CIRCLE_RADIUS = TILE_SIZE // 3

HOST_ADDR = "localhost", 8765
